### ISSUE TITLE
Dominic, do you consent to put this in public domain?

### ISSUE THREAD

**Issue by staltz** [ssbc/ssb-caps#1]
@dominictarr 

This module may seem cosmetic, but now that ssb-server is "just one distribution", as soon as there are newer distributions, people will be copy pasting the caps around, and this can become a bit confusing, there could be a mistake when copying it.

Also, having the caps separate as its own module will help versioning, because updating the major version of this module means a breaking change of the protocol, but updating major version in ssb-server does not signal breaking change in the protocol.

Then, I thought of putting this in public domain, because it's not really code, it's more like open data. You probably would consent to putting this string in public domain, but I need to officially ask anyway. Do you consent? Legal text below. My name is added just because I made this module.

```
 * Legal
 * -----
 *
 * Written in 2015 by 'Dominic Tarr' <dominic.tarr@gmail.com>
 * Contributor: Andre Medeiros <andre@staltz.com>
 *
 * To the extent possible under law, the author(s) have dedicated all copyright
 * and related and neighboring rights to this software to the public domain
 * worldwide. This software is distributed without any warranty.
 *
 * You should have received a copy of the CC0 Public Domain Dedication along
 * with this software. If not, see
 * <http://creativecommons.org/publicdomain/zero/1.0/>.
```

**Comment by dominictarr** [comment]
@staltz yes great idea. there are a couple of places where something wants to just work and so copies in the default cap. those things could just depend on this instead.

**Comment by dominictarr** [comment]
can I make a suggestion though: also include the sign cap. if this was a JSON file, instead of javascript it would be easier to consume from other languages
https://github.com/ssbc/ssb-config/blob/master/defaults.js#L45-L54

**Comment by staltz** [comment]
Will do, thanks!

**Comment by staltz** [comment]
Done!
